GATE_SOL_CONTRACTS = {'2Z': {'chain_name': 'SOL',
        'contract_address': 'J6pQQ3FAcJQeWPPGppWRb4nM8jU3wLyYbRrLh7feMfvd',
        'currency': '2Z',
        'decimals': 8,
        'deposit_disabled': False,
        'withdraw_disabled': False},
 'A47': {'chain_name': 'SOL',
         'contract_address': 'CN162nCPpq3DxPCyKLbAvEJeB1aCxsnVTEG4ZU8vpump',
         'currency': 'A47',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'AAPLX': {'chain_name': 'SOL',
           'contract_address': 'XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp',
           'currency': 'AAPLX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'AART': {'chain_name': 'SOL',
          'contract_address': 'F3nefJBcejYbtdREjui1T9DPh5dBgpkKq7u2GAAMXs5B',
          'currency': 'AART',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'ABBVX': {'chain_name': 'SOL',
           'contract_address': 'XswbinNKyPmzTa5CskMbCPvMW6G5CMnZXZEeQSSQoie',
           'currency': 'ABBVX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'ABTX': {'chain_name': 'SOL',
          'contract_address': 'XsHtf5RpxsQ7jeJ9ivNewouZKJHbPxhPoEy6yYvULr7',
          'currency': 'ABTX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'ACNX': {'chain_name': 'SOL',
          'contract_address': 'Xs5UJzmCRQ8DWZjskExdSQDnbE6iLkRu2jjrRAB1JSU',
          'currency': 'ACNX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'ACS': {'chain_name': 'SOL',
         'contract_address': '5MAYDfq5yxtudAhtfyuMBuHZjgAbaS9tbEyEQYAhDS5y',
         'currency': 'ACS',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'ACT': {'chain_name': 'SOL',
         'contract_address': 'GJAFwWjJ3vnTsrQVabjBVK2TYB1YtRCQXRDfDgUnpump',
         'currency': 'ACT',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'ALCH': {'chain_name': 'SOL',
          'contract_address': 'HNg5PYJmtqcmzXrv6S9zP1CDKk5BgDuyFBxbvNApump',
          'currency': 'ALCH',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'AMZNX': {'chain_name': 'SOL',
           'contract_address': 'Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg',
           'currency': 'AMZNX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'ANON': {'chain_name': 'SOL',
          'contract_address': '9McvH6w97oewLmPxqQEoHUAv3u5iYMyQ9AeZZhguYf1T',
          'currency': 'ANON',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'APRT': {'chain_name': 'SOL',
          'contract_address': 'APTtJyaRX5yGTsJU522N4VYWg3vCvSb65eam5GrPT5Rt',
          'currency': 'APRT',
          'decimals': 6,
          'deposit_disabled': True,
          'withdraw_disabled': False},
 'AQA': {'chain_name': 'SOL',
         'contract_address': 'CHGknFhLgwRcnYGETJwShwAeZssyGE8WXCsgu7fe6X6V',
         'currency': 'AQA',
         'decimals': 9,
         'deposit_disabled': True,
         'withdraw_disabled': False},
 'ARC': {'chain_name': 'SOL',
         'contract_address': '61V8vBaqAGMpgDQi4JcAwo1dmBGHsyhzodcPqnEVpump',
         'currency': 'ARC',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'ASP': {'chain_name': 'SOL',
         'contract_address': 'DJ7vji2BU7RjNgktPAKN4L42CiXTFHEt4Eeeyr5FiTmy',
         'currency': 'ASP',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'ATR': {'chain_name': 'SOL',
         'contract_address': 'ATRLuHph8dxnPny4WSNW7fxkhbeivBrtWbY6BfB4xpLj',
         'currency': 'ATR',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'AVAAI': {'chain_name': 'SOL',
           'contract_address': 'DKu9kykSfbN5LBfFXtNNDPaX35o4Fv6vJ9FKk7pZpump',
           'currency': 'AVAAI',
           'decimals': 6,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'AVGOX': {'chain_name': 'SOL',
           'contract_address': 'XsgSaSvNSqLTtFuyWPBhK9196Xb9Bbdyjj4fH3cPJGo',
           'currency': 'AVGOX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'AWS': {'chain_name': 'SOL',
         'contract_address': 'EgGSqHYuysAEvtP1YxnjcBZNfucT7g4JWzdnURgKSXSr',
         'currency': 'AWS',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'AZNX': {'chain_name': 'SOL',
          'contract_address': 'Xs3ZFkPYT2BN7qBMqf1j1bfTeTm1rFzEFSsQ1z3wAKU',
          'currency': 'AZNX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'BAN': {'chain_name': 'SOL',
         'contract_address': '9PR7nCP9DpcUotnDPVLUBUZKu5WAYkwrCUx9wDnSpump',
         'currency': 'BAN',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'BARSIK': {'chain_name': 'SOL',
            'contract_address': '7ZqzGzTNg5tjK1CHTBdGFHyKjBtXdfvAobuGgdt4pump',
            'currency': 'BARSIK',
            'decimals': 6,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'BEER': {'chain_name': 'SOL',
          'contract_address': 'AujTJJ7aMS8LDo3bFzoyXDwT3jBALUbu4VZhzZdTZLmG',
          'currency': 'BEER',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'BELIEVE': {'chain_name': 'SOL',
             'contract_address': 'BLVxek8YMXUQhcKmMvrFTrzh5FXg8ec88Crp6otEaCMf',
             'currency': 'BELIEVE',
             'decimals': 9,
             'deposit_disabled': False,
             'withdraw_disabled': False},
 'BERT': {'chain_name': 'SOL',
          'contract_address': 'HgBRWfYxEfvPhtqkaeymCQtHCrKE46qQ43pKe8HCpump',
          'currency': 'BERT',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'BIRB': {'chain_name': 'SOL',
          'contract_address': 'G7vQWurMkMMm2dU3iZpXYFTHT9Biio4F4gZCrwFpKNwG',
          'currency': 'BIRB',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'BMT': {'chain_name': 'SOL',
         'contract_address': 'FQgtfugBdpFN7PZ6NdPrZpVLDBrPGxXesi4gVu3vErhY',
         'currency': 'BMT',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'BOME': {'chain_name': 'SOL',
          'contract_address': 'ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82',
          'currency': 'BOME',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'BONK': {'chain_name': 'SOL',
          'contract_address': 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
          'currency': 'BONK',
          'decimals': 5,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'BOOP': {'chain_name': 'SOL',
          'contract_address': 'boopkpWqe68MSxLqBGogs8ZbUDN4GXaLhFwNP7mpP1i',
          'currency': 'BOOP',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'BUCK': {'chain_name': 'SOL',
          'contract_address': 'FLqmVrv6cp7icjobpRMQJMEyjF3kF84QmC4HXpySpump',
          'currency': 'BUCK',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'CATCOIN': {'chain_name': 'SOL',
             'contract_address': '7hWcHohzwtLddDUG81H2PkWq6KEkMtSDNkYXsso18Fy3',
             'currency': 'CATCOIN',
             'decimals': 3,
             'deposit_disabled': False,
             'withdraw_disabled': False},
 'CHATAI': {'chain_name': 'SOL',
            'contract_address': 'DpfVseMtcwUMuMaNUgVoshxQ7Uo4Brtna3k5NaN44U1g',
            'currency': 'CHATAI',
            'decimals': 9,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'CHICKS': {'chain_name': 'SOL',
            'contract_address': 'cxxShYRVcepDudXhe7U62QHvw8uBJoKFifmzggGKVC2',
            'currency': 'CHICKS',
            'decimals': 9,
            'deposit_disabled': True,
            'withdraw_disabled': False},
 'CHILLGUY': {'chain_name': 'SOL',
              'contract_address': 'Df6yfrKC8kZE3KNkrHERKzAetSxbrWeniQfyJY4Jpump',
              'currency': 'CHILLGUY',
              'decimals': 6,
              'deposit_disabled': False,
              'withdraw_disabled': False},
 'CLOUD': {'chain_name': 'SOL',
           'contract_address': 'CLoUDKc4Ane7HeQcPpE3YHnznRxhMimJ4MyaUqyHFzAu',
           'currency': 'CLOUD',
           'decimals': 9,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'CMCSAX': {'chain_name': 'SOL',
            'contract_address': 'XsvKCaNsxg2GN8jjUmq71qukMJr7Q1c5R2Mk9P8kcS8',
            'currency': 'CMCSAX',
            'decimals': 8,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'COINX': {'chain_name': 'SOL',
           'contract_address': 'Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu',
           'currency': 'COINX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'CRCLX': {'chain_name': 'SOL',
           'contract_address': 'XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1',
           'currency': 'CRCLX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'CRWDX': {'chain_name': 'SOL',
           'contract_address': 'Xs7xXqkcK7K8urEqGg52SECi79dRp2cEKKuYjUePYDw',
           'currency': 'CRWDX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'CRWN': {'chain_name': 'SOL',
          'contract_address': 'GDfnEsia2WLAW5t8yx2X5j2mkfA74i5kwGdDuZHt7XmG',
          'currency': 'CRWN',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'CSCOX': {'chain_name': 'SOL',
           'contract_address': 'Xsr3pdLQyXvDJBFgpR5nexCEZwXvigb8wbPYp4YoNFf',
           'currency': 'CSCOX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'CUDIS': {'chain_name': 'SOL',
           'contract_address': 'CudisfkgWvMKnZ3TWf6iCuHm8pN2ikXhDcWytwz6f6RN',
           'currency': 'CUDIS',
           'decimals': 9,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'CWAR': {'chain_name': 'SOL',
          'contract_address': 'HfYFjMKNZygfMC8LsQ8LtpPsPxEJoXJx4M6tqi75Hajo',
          'currency': 'CWAR',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'CWIF': {'chain_name': 'SOL',
          'contract_address': '7atgF8KQo4wJrD5ATGX7t1V2zVvykPJbFfNeVf1icFv1',
          'currency': 'CWIF',
          'decimals': 2,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'DADDY': {'chain_name': 'SOL',
           'contract_address': '4Cnk9EPnW5ixfLZatCPJjDB1PUtcRpVVgTQukm9epump',
           'currency': 'DADDY',
           'decimals': 6,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'DBR': {'chain_name': 'SOL',
         'contract_address': 'DBRiDgJAMsM95moTzJs7M9LnkGErpbv9v6CUR1DXnUu5',
         'currency': 'DBR',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'DEEPSEEK': {'chain_name': 'SOL',
              'contract_address': 'H2gf5g2k4KSWGrAdwtznw7bYkWiszvjistFG447aePiN',
              'currency': 'DEEPSEEK',
              'decimals': 9,
              'deposit_disabled': False,
              'withdraw_disabled': False},
 'DFDVX': {'chain_name': 'SOL',
           'contract_address': 'Xs2yquAgsHByNzx68WJC55WHjHBvG9JsMB7CWjTLyPy',
           'currency': 'DFDVX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'DHRX': {'chain_name': 'SOL',
          'contract_address': 'Xseo8tgCZfkHxWS9xbFYeKFyMSbWEvZGFV1Gh53GtCV',
          'currency': 'DHRX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'DIO': {'chain_name': 'SOL',
         'contract_address': 'BiDB55p4G3n1fGhwKFpxsokBMqgctL4qnZpDH1bVQxMD',
         'currency': 'DIO',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'DOGEGOV': {'chain_name': 'SOL',
             'contract_address': 'KQijDbNJ6rPCqhtXrfH6gKa5cH3a39At8vHq34nnPbF',
             'currency': 'DOGEGOV',
             'decimals': 8,
             'deposit_disabled': False,
             'withdraw_disabled': False},
 'DOOD': {'chain_name': 'SOL',
          'contract_address': 'DvjbEsdca43oQcw2h3HW1CT7N3x5vRcr3QrvTUHnXvgV',
          'currency': 'DOOD',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'DRIFT': {'chain_name': 'SOL',
           'contract_address': 'DriFtupJYLTosbwoN8koMbEYSx54aFAVLddWsbksjwg7',
           'currency': 'DRIFT',
           'decimals': 6,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'ELIZAOS': {'chain_name': 'SOL',
             'contract_address': 'DuMbhu7mvQvqQHGcnikDgb4XegXJRyhUBfdU22uELiZA',
             'currency': 'ELIZAOS',
             'decimals': 9,
             'deposit_disabled': False,
             'withdraw_disabled': False},
 'FARTCOIN': {'chain_name': 'SOL',
              'contract_address': '9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump',
              'currency': 'FARTCOIN',
              'decimals': 6,
              'deposit_disabled': False,
              'withdraw_disabled': False},
 'FDUSD': {'chain_name': 'SOL',
           'contract_address': '9zNQRsGLjNKwCUU5Gq5LR8beUCPzQMVMqKAi3SSZh54u',
           'currency': 'FDUSD',
           'decimals': 6,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'FIDA': {'chain_name': 'SOL',
          'contract_address': 'EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp',
          'currency': 'FIDA',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'FRAG': {'chain_name': 'SOL',
          'contract_address': 'FRAGMEWj2z65qM62zqKhNtwNFskdfKs4ekDUDX3b4VD5',
          'currency': 'FRAG',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'FREE': {'chain_name': 'SOL',
          'contract_address': 'FrEeWJreTHUyPgdJ3DWrdRg6X8qogF5zG5qdxMCgXtTy',
          'currency': 'FREE',
          'decimals': 4,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'GIGA': {'chain_name': 'SOL',
          'contract_address': '63LfDmNb3MQ8mw9MtZ2To9bEA2M71kZUUGq5tiJxcqj9',
          'currency': 'GIGA',
          'decimals': 5,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'GLDX': {'chain_name': 'SOL',
          'contract_address': 'Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re',
          'currency': 'GLDX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'GMAI': {'chain_name': 'SOL',
          'contract_address': 'GMai1NvHreNe135cvxya1gHaUJZiT1NAvbJkF4hPHQJ9',
          'currency': 'GMAI',
          'decimals': 6,
          'deposit_disabled': True,
          'withdraw_disabled': False},
 'GMT': {'chain_name': 'SOL',
         'contract_address': '7i5KKsX2weiTkry7jA4ZwSuXGhs5eJBEjY8vVxR4pfRx',
         'currency': 'GMT',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'GOAT': {'chain_name': 'SOL',
          'contract_address': 'CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump',
          'currency': 'GOAT',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'GOHOME': {'chain_name': 'SOL',
            'contract_address': '2Wu1g2ft7qZHfTpfzP3wLdfPeV1is4EwQ3CXBfRYAciD',
            'currency': 'GOHOME',
            'decimals': 6,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'GOOGLX': {'chain_name': 'SOL',
            'contract_address': 'XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN',
            'currency': 'GOOGLX',
            'decimals': 8,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'GORK': {'chain_name': 'SOL',
          'contract_address': '38PgzpJYu2HkiYvV8qePFakB8tuobPdGm2FFEn7Dpump',
          'currency': 'GORK',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'GRASS': {'chain_name': 'SOL',
           'contract_address': 'Grass7B4RdKfBCjTKgSqnXkqjwiGvQyFbuSCUJr3XXjs',
           'currency': 'GRASS',
           'decimals': 9,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'GRIFFAIN': {'chain_name': 'SOL',
              'contract_address': 'KENJSUYLASHUMfHyy5o4Hp2FdNqZg1AsUPhfH2kYvEP',
              'currency': 'GRIFFAIN',
              'decimals': 6,
              'deposit_disabled': False,
              'withdraw_disabled': False},
 'GTBTC': {'chain_name': 'SOL',
           'contract_address': 'gtBTCGWvSRYYoZpU9UZj6i3eUGUpgksXzzsbHk2K9So',
           'currency': 'GTBTC',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'GTDOGE': {'chain_name': 'SOL',
            'contract_address': 'GtDogeoPcfYRU2LmJqyLsLnD3QM1N5fUYta3C4x8st1',
            'currency': 'GTDOGE',
            'decimals': 8,
            'deposit_disabled': True,
            'withdraw_disabled': True},
 'GTSOL': {'chain_name': 'SOL',
           'contract_address': 'gateMurAxe4YFoUR6J63gXGKtkbTfdkMdLjZrCmThFP',
           'currency': 'GTSOL',
           'decimals': 9,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'GTXRP': {'chain_name': 'SOL',
           'contract_address': 'GTxrpyWoLoKze64984JdxJQXZS8TU6PV8t6ZvGKdi8BC',
           'currency': 'GTXRP',
           'decimals': 6,
           'deposit_disabled': True,
           'withdraw_disabled': True},
 'HAMSTER': {'chain_name': 'SOL',
             'contract_address': 'APQd2J9FQLbMy4jYa6A4oe2jXVvKgy2uGKfQbhdGeXpk',
             'currency': 'HAMSTER',
             'decimals': 8,
             'deposit_disabled': True,
             'withdraw_disabled': False},
 'HDX': {'chain_name': 'SOL',
         'contract_address': 'XszjVtyhowGjSC5odCqBpW1CtXXwXjYokymrk7fGKD3',
         'currency': 'HDX',
         'decimals': 8,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'HNT': {'chain_name': 'SOL',
         'contract_address': 'hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux',
         'currency': 'HNT',
         'decimals': 8,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'HOLO': {'chain_name': 'SOL',
          'contract_address': '69RX85eQoEsnZvXGmLNjYcWgVkp9r2JjahVm99KbJETU',
          'currency': 'HOLO',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'HONEY': {'chain_name': 'SOL',
           'contract_address': '4vMsoUT2BWatFweudnQM1xedRLfJgJ7hswhcpz4xgBTy',
           'currency': 'HONEY',
           'decimals': 9,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'HONX': {'chain_name': 'SOL',
          'contract_address': 'XsRbLZthfABAPAfumWNEJhPyiKDW6TvDVeAeW7oKqA2',
          'currency': 'HONX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'HOODX': {'chain_name': 'SOL',
           'contract_address': 'XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg',
           'currency': 'HOODX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'HOOLI': {'chain_name': 'SOL',
           'contract_address': 'FPJfY8mMTRwaePD2f46TFLqVov4X9svBaUgR1a8oTwTF',
           'currency': 'HOOLI',
           'decimals': 9,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'HUMA': {'chain_name': 'SOL',
          'contract_address': 'HUMA1821qVDKta3u2ovmfDQeW2fSQouSKE8fkF44wvGw',
          'currency': 'HUMA',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'HVLO': {'chain_name': 'SOL',
          'contract_address': 'Gdck9KXSSiMMhNyjUjo4sVT1GDzeZnZP2yse9jhax3GR',
          'currency': 'HVLO',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'IO': {'chain_name': 'SOL',
        'contract_address': 'BZLbGTNCSFfoth2GYDtwr7e4imWzpR5jqcUuGEwr646K',
        'currency': 'IO',
        'decimals': 8,
        'deposit_disabled': False,
        'withdraw_disabled': False},
 'J': {'chain_name': 'SOL',
       'contract_address': 'Jambjx1oJoZNBZiqbiF9TqgatEZPdyfvYa9WVsKNzUh',
       'currency': 'J',
       'decimals': 9,
       'deposit_disabled': False,
       'withdraw_disabled': False},
 'JELLYJELLY': {'chain_name': 'SOL',
                'contract_address': 'FeR8VBqNRSUD5NtXAj2n3j1dAHkZHfyDktKuLXD4pump',
                'currency': 'JELLYJELLY',
                'decimals': 6,
                'deposit_disabled': False,
                'withdraw_disabled': False},
 'JTO': {'chain_name': 'SOL',
         'contract_address': 'jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL',
         'currency': 'JTO',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'JUP': {'chain_name': 'SOL',
         'contract_address': 'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',
         'currency': 'JUP',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'KMNO': {'chain_name': 'SOL',
          'contract_address': 'KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS',
          'currency': 'KMNO',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'KOX': {'chain_name': 'SOL',
         'contract_address': 'XsaBXg8dU5cPM6ehmVctMkVqoiRG2ZjMo1cyBJ3AykQ',
         'currency': 'KOX',
         'decimals': 8,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'KZEN': {'chain_name': 'SOL',
          'contract_address': 'kZEn3aDxEzcFADPe2VQ6WcJRbS1hVGjUcgCw4HiuYSU',
          'currency': 'KZEN',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'LABUBU': {'chain_name': 'SOL',
            'contract_address': 'JB2wezZLdzWfnaCfHxLg193RS3Rh51ThiXxEDWQDpump',
            'currency': 'LABUBU',
            'decimals': 6,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'LAYER': {'chain_name': 'SOL',
           'contract_address': 'LAYER4xPpTCb3QL8S9u41EAhAX7mhBn8Q6xMTwY2Yzc',
           'currency': 'LAYER',
           'decimals': 9,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'LIKE': {'chain_name': 'SOL',
          'contract_address': '3bRTivrVsitbmCTGtqwp7hxXPsybkjn4XLNtPsHqa3zR',
          'currency': 'LIKE',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'LLYX': {'chain_name': 'SOL',
          'contract_address': 'Xsnuv4omNoHozR6EEW5mXkw8Nrny5rB3jVfLqi6gKMH',
          'currency': 'LLYX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'LOULOU': {'chain_name': 'SOL',
            'contract_address': '7BMb4jNt2tQG81jX7W22H2h2UyL4SW9QJgz25HRhpump',
            'currency': 'LOULOU',
            'decimals': 6,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'MAD': {'chain_name': 'SOL',
         'contract_address': 'madHpjRn6bd8t78Rsy7NuSuNwWa2HU8ByPobZprHbHv',
         'currency': 'MAD',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'MANEKI': {'chain_name': 'SOL',
            'contract_address': '25hAyBQfoDhfWx9ay6rarbgvWGwDdNqcHsXS3jQ3mTDJ',
            'currency': 'MANEKI',
            'decimals': 5,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'MAX': {'chain_name': 'SOL',
         'contract_address': 'XsApJFV9MAktqnAc6jqzsHVujxkGm9xcSUffaBoYLKC',
         'currency': 'MAX',
         'decimals': 8,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'MAY': {'chain_name': 'SOL',
         'contract_address': 'FJz7ptUR1FwxSHbb8Sfd5Cn6Zt4TqucJZKLqU4n66gdq',
         'currency': 'MAY',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'MCDX': {'chain_name': 'SOL',
          'contract_address': 'XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2',
          'currency': 'MCDX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'MDF': {'chain_name': 'SOL',
         'contract_address': 'ALQ9KMWjFmxVbew3vMkJj3ypbAKuorSgGst6svCHEe2z',
         'currency': 'MDF',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'ME': {'chain_name': 'SOL',
        'contract_address': 'MEFNBXixkEbait3xn9bkm8WsJzXtVsaJEn4c8Sam21u',
        'currency': 'ME',
        'decimals': 6,
        'deposit_disabled': False,
        'withdraw_disabled': False},
 'MELANIA': {'chain_name': 'SOL',
             'contract_address': 'FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P',
             'currency': 'MELANIA',
             'decimals': 6,
             'deposit_disabled': False,
             'withdraw_disabled': False},
 'MER': {'chain_name': 'SOL',
         'contract_address': 'MERt85fc5boKw3BW1eYdxonEuJNvXbiMbs6hvheau5K',
         'currency': 'MER',
         'decimals': 6,
         'deposit_disabled': True,
         'withdraw_disabled': False},
 'MET': {'chain_name': 'SOL',
         'contract_address': 'METvsvVRapdj9cFLzq4Tr43xK4tAjQfwX76z3n6mWQL',
         'currency': 'MET',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'METAX': {'chain_name': 'SOL',
           'contract_address': 'Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu',
           'currency': 'METAX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'MEW': {'chain_name': 'SOL',
         'contract_address': 'MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5',
         'currency': 'MEW',
         'decimals': 5,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'MF': {'chain_name': 'SOL',
        'contract_address': 'moonThZEkkTVoNB7v6YVCQiT56JYDZ1oN185ba3WizL',
        'currency': 'MF',
        'decimals': 4,
        'deposit_disabled': False,
        'withdraw_disabled': False},
 'MIRAI': {'chain_name': 'SOL',
           'contract_address': '5evN2exivZXJfLaA1KhHfiJKWfwH8znqyH36w1SFz89Y',
           'currency': 'MIRAI',
           'decimals': 6,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'MNDE': {'chain_name': 'SOL',
          'contract_address': 'MNDEFzGvMt87ueuHvVU9VcTqsAP5b3fTGPsHuuPA5ey',
          'currency': 'MNDE',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'MOODENG': {'chain_name': 'SOL',
             'contract_address': 'ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY',
             'currency': 'MOODENG',
             'decimals': 6,
             'deposit_disabled': False,
             'withdraw_disabled': False},
 'MPLX': {'chain_name': 'SOL',
          'contract_address': 'METAewgxyPbgwsseH8T16a39CQ5VyVxZi9zXiDPY18m',
          'currency': 'MPLX',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'MSOL': {'chain_name': 'SOL',
          'contract_address': 'mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So',
          'currency': 'MSOL',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'MSTRX': {'chain_name': 'SOL',
           'contract_address': 'XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ',
           'currency': 'MSTRX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'MTOS': {'chain_name': 'SOL',
          'contract_address': 'HcQbgvMTCNDgMDY6GAFzP1WwCNZeMoEwZfUuHepzC9L5',
          'currency': 'MTOS',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'MYRO': {'chain_name': 'SOL',
          'contract_address': 'Bm3dgkZrjH7eaz1GBH1R2ZHkp7nZUoPNJhjekoxepump',
          'currency': 'MYRO',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'MYROOLD': {'chain_name': 'SOL',
             'contract_address': 'HhJpBhRRn4g56VsyLuT8DL5Bv31HkXqsrahTTUCZeZg4',
             'currency': 'MYROOLD',
             'decimals': 9,
             'deposit_disabled': True,
             'withdraw_disabled': False},
 'NATIX': {'chain_name': 'SOL',
           'contract_address': 'FRySi8LPkuByB7VPSCCggxpewFUeeJiwEGRKKuhwpKcX',
           'currency': 'NATIX',
           'decimals': 6,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'NC': {'chain_name': 'SOL',
        'contract_address': 'B89Hd5Juz7JP2dxCZXFJWk4tMTcbw7feDhuWGb3kq5qE',
        'currency': 'NC',
        'decimals': 9,
        'deposit_disabled': False,
        'withdraw_disabled': False},
 'NEKO': {'chain_name': 'SOL',
          'contract_address': '53kC8TJ5gfBPBPN4afNA1k433vL7ZhNHaw9NGh3HBo9N',
          'currency': 'NEKO',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'NEON': {'chain_name': 'SOL',
          'contract_address': 'NeonTjSjsuo3rexg9o6vHuMXw62f9V7zvmu8M8Zut44',
          'currency': 'NEON',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': True},
 'NFLXX': {'chain_name': 'SOL',
           'contract_address': 'XsEH7wWfJJu2ZT3UCFeVfALnVA6CP5ur7Ee11KmzVpL',
           'currency': 'NFLXX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'NOBODY': {'chain_name': 'SOL',
            'contract_address': 'C29ebrgYjYoJPMGPnPSGY1q3mMGk4iDSqnQeQQA7moon',
            'currency': 'NOBODY',
            'decimals': 9,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'NOS': {'chain_name': 'SOL',
         'contract_address': 'nosXBVoaCTtYdLvKY6Csb4AC8JCdQKKAaWYtx2ZMoo7',
         'currency': 'NOS',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'NVDAX': {'chain_name': 'SOL',
           'contract_address': 'Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh',
           'currency': 'NVDAX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'NYAN': {'chain_name': 'SOL',
          'contract_address': 'NYANpAp9Cr7YarBNrby7Xx4xU6No6JKTBuohNA3yscP',
          'currency': 'NYAN',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'ORCA': {'chain_name': 'SOL',
          'contract_address': 'orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE',
          'currency': 'ORCA',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'OXY': {'chain_name': 'SOL',
         'contract_address': 'z3dn17yLaGMKffVogeFHQ9zWVcXgqgf3PQnDsNs2g6M',
         'currency': 'OXY',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'PAWS': {'chain_name': 'SOL',
          'contract_address': 'PAWSxhjTyNJELywYiYTxCN857utnYmWXu7Q59Vgn6ZQ',
          'currency': 'PAWS',
          'decimals': 6,
          'deposit_disabled': True,
          'withdraw_disabled': False},
 'PENGU': {'chain_name': 'SOL',
           'contract_address': '2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv',
           'currency': 'PENGU',
           'decimals': 6,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'PENGUIN': {'chain_name': 'SOL',
             'contract_address': '8Jx8AAHj86wbQgUTjGuj6GTTL5Ps3cqxKRTvpaJApump',
             'currency': 'PENGUIN',
             'decimals': 6,
             'deposit_disabled': False,
             'withdraw_disabled': False},
 'PEPX': {'chain_name': 'SOL',
          'contract_address': 'Xsv99frTRUeornyvCfvhnDesQDWuvns1M852Pez91vF',
          'currency': 'PEPX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'PGX': {'chain_name': 'SOL',
         'contract_address': 'XsYdjDjNUygZ7yGKfQaB6TxLh2gC6RRjzLtLAGJrhzV',
         'currency': 'PGX',
         'decimals': 8,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'PIPE': {'chain_name': 'SOL',
          'contract_address': '7s9MoSt7VV1J3jVNnw2AyocsQDBdCkPYz5apQDPKy9i5',
          'currency': 'PIPE',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'PIPPIN': {'chain_name': 'SOL',
            'contract_address': 'Dfh5DzRgSvvCFDoYc2ciTkMrbDfRKybA4SoFbPmApump',
            'currency': 'PIPPIN',
            'decimals': 6,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'PMX': {'chain_name': 'SOL',
         'contract_address': 'Xsba6tUnSjDae2VcopDB6FGGDaxRrewFCDa5hKn5vT3',
         'currency': 'PMX',
         'decimals': 8,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'PNUT': {'chain_name': 'SOL',
          'contract_address': '2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump',
          'currency': 'PNUT',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'PONKE': {'chain_name': 'SOL',
           'contract_address': '5z3EqYQo9HiCEs3R84RCDMu2n7anpDMxRhdK8PSWmrRC',
           'currency': 'PONKE',
           'decimals': 9,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'POPCAT': {'chain_name': 'SOL',
            'contract_address': '7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr',
            'currency': 'POPCAT',
            'decimals': 9,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'PORT': {'chain_name': 'SOL',
          'contract_address': 'PoRTjZMPXb9T7dyU7tpLEZRQj7e6ssfAE62j2oQuc6y',
          'currency': 'PORT',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'PORTALS': {'chain_name': 'SOL',
             'contract_address': 'PRTLSwfLzpVGSAQiUfXEenJkq1cwTsEcsn1hPL9zwwg',
             'currency': 'PORTALS',
             'decimals': 9,
             'deposit_disabled': False,
             'withdraw_disabled': False},
 'PRCL': {'chain_name': 'SOL',
          'contract_address': '4LLbsb5ReP3yEtYzmXewyGjcir5uXtKFURtaEUVC2AHs',
          'currency': 'PRCL',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'PRL': {'chain_name': 'SOL',
         'contract_address': 'PERLEQKUNUp1dgFZ8EvyXHdN9d6ZQqfGxALDvfs6pDs',
         'currency': 'PRL',
         'decimals': 8,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'PUMP': {'chain_name': 'SOL',
          'contract_address': 'pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn',
          'currency': 'PUMP',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'PYTH': {'chain_name': 'SOL',
          'contract_address': 'HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3',
          'currency': 'PYTH',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'PYUSD': {'chain_name': 'SOL',
           'contract_address': '2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo',
           'currency': 'PYUSD',
           'decimals': 6,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'QKA': {'chain_name': 'SOL',
         'contract_address': 'mtQ5jWgCqrgBiSut29b4HV19RkMBGA6vidwTMqhNmyy',
         'currency': 'QKA',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'QQQX': {'chain_name': 'SOL',
          'contract_address': 'Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ',
          'currency': 'QQQX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'RAY': {'chain_name': 'SOL',
         'contract_address': '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
         'currency': 'RAY',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'READY': {'chain_name': 'SOL',
           'contract_address': 'HKJHsYJHMVK5VRyHHk5GhvzY9tBAAtPvDkZfDH6RLDTd',
           'currency': 'READY',
           'decimals': 9,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'RENDER': {'chain_name': 'SOL',
            'contract_address': 'rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof',
            'currency': 'RENDER',
            'decimals': 8,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'RFC': {'chain_name': 'SOL',
         'contract_address': 'C3DwDjT17gDvvCYC2nsdGHxDHVmQRdhKfpAdqQ29pump',
         'currency': 'RFC',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'ROA': {'chain_name': 'SOL',
         'contract_address': '5tB5D6DGJMxxHYmNkfJNG237x6pZGEwTzGpUUh62yQJ7',
         'currency': 'ROA',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'ROAM': {'chain_name': 'SOL',
          'contract_address': 'RoamA1USA8xjvpTJZ6RvvxyDRzNh6GCA1zVGKSiMVkn',
          'currency': 'ROAM',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'RZTO': {'chain_name': 'SOL',
          'contract_address': '2qpqweHfSKUvZFGQL3D7aadD5i5dDN8kz9xdZGraGAxC',
          'currency': 'RZTO',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'SAMO': {'chain_name': 'SOL',
          'contract_address': '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
          'currency': 'SAMO',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'SAROS': {'chain_name': 'SOL',
           'contract_address': 'SarosY6Vscao718M4A778z4CGtvcwcGef5M9MEH1LGL',
           'currency': 'SAROS',
           'decimals': 6,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'SBR': {'chain_name': 'SOL',
         'contract_address': 'Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1',
         'currency': 'SBR',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'SCIHUB': {'chain_name': 'SOL',
            'contract_address': 'GxdTh6udNstGmLLk9ztBb6bkrms7oLbrJp5yzUaVpump',
            'currency': 'SCIHUB',
            'decimals': 6,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'SCRAT': {'chain_name': 'SOL',
           'contract_address': '3GEznP41VaAGv9yRdBiuYdA8zkffNc8b7DzNJgFbH4Kh',
           'currency': 'SCRAT',
           'decimals': 6,
           'deposit_disabled': True,
           'withdraw_disabled': False},
 'SHARK': {'chain_name': 'SOL',
           'contract_address': 'SHARKSYJjqaNyxVfrpnBN9pjgkhwDhatnMyicWPnr1s',
           'currency': 'SHARK',
           'decimals': 6,
           'deposit_disabled': True,
           'withdraw_disabled': False},
 'SHDW': {'chain_name': 'SOL',
          'contract_address': 'SHDWyBxihqiCj6YekG2GUr7wqKLeLAMK1gHZck9pL6y',
          'currency': 'SHDW',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'SKR': {'chain_name': 'SOL',
         'contract_address': 'SKRbvo6Gf7GondiT3BbTfuRDPqLWei4j2Qy2NPGZhW3',
         'currency': 'SKR',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'SLERF_OLD': {'chain_name': 'SOL',
               'contract_address': '7BgBvyjrZX1YKz4oh9mjb8ZScatkkwb8DzFx7LoiVkM3',
               'currency': 'SLERF_OLD',
               'decimals': 9,
               'deposit_disabled': True,
               'withdraw_disabled': False},
 'SLRS': {'chain_name': 'SOL',
          'contract_address': 'SLRSSpSLUTP7okbCUBYStWCo1vUgyt775faPqz8HUMr',
          'currency': 'SLRS',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'SLX': {'chain_name': 'SOL',
         'contract_address': 'SLXdx4BUt2v9uJQNzWqSfzTJ9UKLUDsvxHFMEEdrfgq',
         'currency': 'SLX',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'SNTR': {'chain_name': 'SOL',
          'contract_address': 'SENBBKVCM7homnf5RX9zqpf1GFe935hnbU4uVzY1Y6M',
          'currency': 'SNTR',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'SONIC': {'chain_name': 'SOL',
           'contract_address': 'SonicxvLud67EceaEzCLRnMTBqzYUUYNr93DBkBdDES',
           'currency': 'SONIC',
           'decimals': 9,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'SOON': {'chain_name': 'SOL',
          'contract_address': '4eDf52YYzL6i6gbZ6FXqrLUPXbtP61f1gPSFM66M4XHe',
          'currency': 'SOON',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'SPCXON': {'chain_name': 'SOL',
            'contract_address': 'wzAyQTorWyoVXuJKj2x8EqKEGJpS13z6EWE9z5Aondo',
            'currency': 'SPCXON',
            'decimals': 9,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'SPCXX': {'chain_name': 'SOL',
           'contract_address': 'Xs3oZwbHvqis4NYcf4YKWmEia2eC84wSiVrcYcTqpH8',
           'currency': 'SPCXX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'SPYX': {'chain_name': 'SOL',
          'contract_address': 'XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W',
          'currency': 'SPYX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'STIK': {'chain_name': 'SOL',
          'contract_address': '8BMzMi2XxZn9afRaMx5Z6fauk9foHXqV5cLTCYWRcVje',
          'currency': 'STIK',
          'decimals': 9,
          'deposit_disabled': True,
          'withdraw_disabled': False},
 'STREAM': {'chain_name': 'SOL',
            'contract_address': 'STREAMribRwybYpMmSYoCsQUdr6MZNXEqHgm7p1gu9M',
            'currency': 'STREAM',
            'decimals': 6,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'STSOL': {'chain_name': 'SOL',
           'contract_address': '7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj',
           'currency': 'STSOL',
           'decimals': 9,
           'deposit_disabled': True,
           'withdraw_disabled': False},
 'SVT': {'chain_name': 'SOL',
         'contract_address': 'svtMpL5eQzdmB3uqK9NXaQkq8prGZoKQFNVJghdWCkV',
         'currency': 'SVT',
         'decimals': 6,
         'deposit_disabled': True,
         'withdraw_disabled': False},
 'SWARMS': {'chain_name': 'SOL',
            'contract_address': '74SBV4zDXxTRgv1pEMoECskKBkZHc2yGPnc7GYVepump',
            'currency': 'SWARMS',
            'decimals': 6,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'TAI': {'chain_name': 'SOL',
         'contract_address': 'Hax9LTgsQkze1YFychnBLtFH8gYbQKtKfWKKg2SP6gdD',
         'currency': 'TAI',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'TNSR': {'chain_name': 'SOL',
          'contract_address': 'TNSRxcUxoT9xBG3de7PiJyTDYu7kskLqcpddxnEJAS6',
          'currency': 'TNSR',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'TQQQX': {'chain_name': 'SOL',
           'contract_address': 'XsjQP3iMAaQ3kQScQKthQpx9ALRbjKAjQtHg6TFomoc',
           'currency': 'TQQQX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'TROLL': {'chain_name': 'SOL',
           'contract_address': '5UUH9RTDiSpq6HKS6bp4NdU9PNJpXRXuiw6ShBTBhgH2',
           'currency': 'TROLL',
           'decimals': 6,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'TRUMP': {'chain_name': 'SOL',
           'contract_address': '6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN',
           'currency': 'TRUMP',
           'decimals': 6,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'TSLAX': {'chain_name': 'SOL',
           'contract_address': 'XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB',
           'currency': 'TSLAX',
           'decimals': 8,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'UNHX': {'chain_name': 'SOL',
          'contract_address': 'XszvaiXGPwvk2nwb3o9C1CX4K6zH8sez11E6uyup6fe',
          'currency': 'UNHX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'URANUS': {'chain_name': 'SOL',
            'contract_address': 'BFgdzMkTPdKKJeTipv2njtDEwhKxkgFueJQfJGt1jups',
            'currency': 'URANUS',
            'decimals': 6,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'USD1': {'chain_name': 'SOL',
          'contract_address': 'USD1ttGY1N17NEEHLmELoaybftRBUSErhqYiQzvEmuB',
          'currency': 'USD1',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'USDC': {'chain_name': 'SOL',
          'contract_address': 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
          'currency': 'USDC',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'USDG': {'chain_name': 'SOL',
          'contract_address': '2u1tszSeqZ3qBWF3uNGPFc8TzMk2tdiwknnRMWGWjGWH',
          'currency': 'USDG',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'USDPT': {'chain_name': 'SOL',
           'contract_address': 'HVWf8JmLoHs99Lw8Psf3fyqAtA4crWxCPkrmSdNjhNH3',
           'currency': 'USDPT',
           'decimals': 6,
           'deposit_disabled': False,
           'withdraw_disabled': False},
 'USDT': {'chain_name': 'SOL',
          'contract_address': 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
          'currency': 'USDT',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'USELESS': {'chain_name': 'SOL',
             'contract_address': 'Dz9mQ9NzkBcCsuGPFJ3r1bS4wgqKMHBPiVuniW8Mbonk',
             'currency': 'USELESS',
             'decimals': 6,
             'deposit_disabled': False,
             'withdraw_disabled': False},
 'VDR': {'chain_name': 'SOL',
         'contract_address': '5a6LTLwdMJBY2JDLjw8B1w4JwFRdZszGF9W56ZzrriS1',
         'currency': 'VDR',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'VINE': {'chain_name': 'SOL',
          'contract_address': '6AJcP7wuLwmRYLBNbi825wgguaPsWzPBEHcHndpRpump',
          'currency': 'VINE',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'VOID': {'chain_name': 'SOL',
          'contract_address': '6gh8b2mqUrVb6Ew8Mwt89tNyN9keCDNstzT5cdp5pump',
          'currency': 'VOID',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'VTIX': {'chain_name': 'SOL',
          'contract_address': 'XsssYEQjzxBCFgvYFFNuhJFBeHNdLWYeUSP8F45cDr9',
          'currency': 'VTIX',
          'decimals': 8,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'W': {'chain_name': 'SOL',
       'contract_address': '85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ',
       'currency': 'W',
       'decimals': 6,
       'deposit_disabled': False,
       'withdraw_disabled': False},
 'WAG': {'chain_name': 'SOL',
         'contract_address': '5tN42n9vMi6ubp67Uy4NnmM5DMZYN8aS8GeB3bEDHr6E',
         'currency': 'WAG',
         'decimals': 9,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'WENSOL': {'chain_name': 'SOL',
            'contract_address': 'WENWENvqqNya429ubCdR81ZmD69brwQaaBYY6p3LCpk',
            'currency': 'WENSOL',
            'decimals': 5,
            'deposit_disabled': False,
            'withdraw_disabled': False},
 'WET': {'chain_name': 'SOL',
         'contract_address': 'WETZjtprkDMCcUxPi9PfWnowMRZkiGGHDb9rABuRZ2U',
         'currency': 'WET',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'WIF': {'chain_name': 'SOL',
         'contract_address': 'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm',
         'currency': 'WIF',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False},
 'WLFI': {'chain_name': 'SOL',
          'contract_address': 'WLFinEv6ypjkczcS83FZqFpgFZYwQXutRbxGe7oC16g',
          'currency': 'WLFI',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'XLAB': {'chain_name': 'SOL',
          'contract_address': 'XLnpFRQ3rSWupCRjuQfx74mgVoT3ezVJKE1CogRZxhH',
          'currency': 'XLAB',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'XTAG': {'chain_name': 'SOL',
          'contract_address': '5gs8nf4wojB5EXgDUWNLwXpknzgV2YWDhveAeBZpVLbp',
          'currency': 'XTAG',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'ZBC': {'chain_name': 'SOL',
         'contract_address': 'zebeczgi5fSEtbpfQKVZKCJ3WgYXxjkMUkNNx7fLKAF',
         'currency': 'ZBC',
         'decimals': 9,
         'deposit_disabled': True,
         'withdraw_disabled': False},
 'ZBCN': {'chain_name': 'SOL',
          'contract_address': 'ZBCNpuD7YMXzTHB2fhGkGi78MNsHGLRXUhRewNRm9RU',
          'currency': 'ZBCN',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'ZEEP_OLD': {'chain_name': 'SOL',
              'contract_address': 'FHAeF63cELMnm9HAHPLEWJGrGpBEYkdcvN3cLQGTCA6j',
              'currency': 'ZEEP_OLD',
              'decimals': 6,
              'deposit_disabled': True,
              'withdraw_disabled': True},
 'ZEREBRO': {'chain_name': 'SOL',
             'contract_address': '8x5VqbHA8D7NkD52uNuS5nnt3PwA8pLD34ymskeSo2Wn',
             'currency': 'ZEREBRO',
             'decimals': 6,
             'deposit_disabled': False,
             'withdraw_disabled': False},
 'ZERO': {'chain_name': 'SOL',
          'contract_address': '93RC484oMK5T9H89rzT5qiAXKHGP9jscXfFfrihNbe57',
          'currency': 'ZERO',
          'decimals': 9,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'ZEUS': {'chain_name': 'SOL',
          'contract_address': 'ZEUS1aR7aX8DFFJf5QjWj2ftDDdNTroMNGo8YoQm3Gq',
          'currency': 'ZEUS',
          'decimals': 6,
          'deposit_disabled': False,
          'withdraw_disabled': False},
 'ZEX': {'chain_name': 'SOL',
         'contract_address': 'ZEXy1pqteRu3n13kdyh4LwPQknkFk3GzmMYMuNadWPo',
         'currency': 'ZEX',
         'decimals': 6,
         'deposit_disabled': False,
         'withdraw_disabled': False}
}


